be-feat/userAddCode
UOS-CSDESIGN/Epimetheus pull request #41
Opened 2023-10-25 12:22 UTC by humang

## :racehorse: 작업 분류
- [X] 기능 개발 
- [ ] 리팩토링/스타일 수정
- [ ] 테스트
- [ ] 버그수정
- [ ] 기타(작성: )

<br/>

## :package: 변경사항을 설명해주세요
- [X] 유저가 subTask에 대해 자신이 작성한 code를 db에 저장할 수 있는 메소드가 추가되었습니다. 
- 추가로 cors의 설정방식이 바뀌면서 전체 http메소드에 대해 설정이 일괄적용되게 되었습니다
<br/>

## 🐞 직면했던 문제
- 이후의 연계되는 서비스에 대해 어떻게 처리할지 고민되는 상태에서 추가적인 서비스를 구성한다면 바로 적용할 수 있도록 준비해두었다. 

<br/>

## 🔷 Workflow Automation
- #close JIRA-91
- #close JIRA-37

2023-10-25 15:18 UTC, tank3a requested changes
Review 확인해주세요

2023-10-25 15:18 UTC, tank3a commented on backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/TaskController.java
> +            return ResponseEntity.ok().body("sucess");
오타있네요 success입니다

2023-10-25 15:18 UTC, tank3a commented on backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/TaskController.java
> +        if(response.equals("not code")){
차라리 body부분이 현재 response를 그대로 넣는 방식을 할거라면, 앞에 ResponseEntity 객체를 만들어 먼저 body는 service의 응답으로 바로 넣고, 이후 분기점에서 statuscode를 주입하는 방식으로 하는 것이 깔끔할 것 같습니다.

2023-10-25 15:18 UTC, tank3a commented on backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskServiceStreamImpl.java
> +                return "sucess";
여기도 오타가 있네요

2023-10-26 10:54 UTC, humang commented on backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskServiceStreamImpl.java
> +                return "sucess";
오타 해결했습니다

2023-10-26 10:55 UTC, humang commented on backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/TaskController.java
> +        if(response.equals("not code")){
형식을 바꾸어 놓았습니다

2023-10-26 10:56 UTC, tank3a approved these changes
고생했습니다

2023-10-26 10:57 UTC, CsLsj approved these changes
Gooooood

2023-10-26 10:58 UTC, merged